services:
  xtdb:
    build:
      context: ../docker/standalone
    command: ["playground", "--port", "5439"]
    healthcheck:
      test: ["CMD-SHELL", "timeout 1 bash -c '</dev/tcp/localhost/5439'"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 15s

  js:
    build:
      context: js
    environment:
      PG_HOST: xtdb
      PG_PORT: 5439

  python:
    build:
      context: python
    environment:
      PG_HOST: xtdb
      PG_PORT: 5439

  elixir:
    build:
      context: elixr
    environment:
      PG_HOST: xtdb
      PG_PORT: 5439
