name: XTDB SLT
run-name: XTDB SLT

on:
  schedule:
    - cron:  '0/5 * * * *'

jobs:
  slt-test-dir:
    name: SLT Test Dir
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: "cron test"

